Repository woowa-techcamp-2022/android-banchan-04, pull requests merged in 2022-08, with the labels that each got.

#2 프로젝트 생성
  .gitignore
  app/.gitignore
  app/build.gradle
  app/proguard-rules.pro
  app/src/androidTest/java/com/woowa/banchan/ExampleInstrumentedTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/woowa/banchan/MainActivity.kt
  app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  app/src/main/res/xml/backup_rules.xml
  app/src/main/res/xml/data_extraction_rules.xml
  app/src/test/java/com/woowa/banchan/ExampleUnitTest.kt
  build.gradle
  gradle.properties
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
Labels: chore

#5 버전 관리 설정
  app/build.gradle
  app/build.gradle.kts
  app/proguard-rules.pro
  app/src/androidTest/java/com/woowa/banchan/ExampleInstrumentedTest.kt
  app/src/main/java/com/woowa/banchan/MainActivity.kt
  app/src/test/java/com/woowa/banchan/ExampleUnitTest.kt
  build.gradle
  build.gradle.kts
  buildSrc/build.gradle.kts
  buildSrc/src/main/java/Configs.kt
  buildSrc/src/main/java/Dependencies.kt
  settings.gradle.kts
Labels: chore

#6 멀티모듈 설정
  app/build.gradle.kts
  build.gradle.kts
  data/.gitignore
  data/build.gradle.kts
  data/src/main/java/com/woowa/data/MyClass.kt
  domain/.gitignore
  domain/build.gradle.kts
  domain/src/main/java/com/woowa/domain/MyClass.kt
  settings.gradle.kts
Labels: chore

#10 icon, color, theme, font 추가 및 변경
  app/src/main/res/drawable/ic_cart.xml
  app/src/main/res/drawable/ic_check.xml
  app/src/main/res/drawable/ic_checkbox.xml
  app/src/main/res/drawable/ic_checkbox_empty.xml
  app/src/main/res/drawable/ic_close.xml
  app/src/main/res/drawable/ic_down.xml
  app/src/main/res/drawable/ic_grid_selected.xml
  app/src/main/res/drawable/ic_grid_unselected.xml
  app/src/main/res/drawable/ic_left_arrow.xml
  app/src/main/res/drawable/ic_linear_selected.xml
  app/src/main/res/drawable/ic_linear_unselected.xml
  app/src/main/res/drawable/ic_reload.xml
  app/src/main/res/drawable/ic_right_arrow.xml
  app/src/main/res/drawable/ic_user.xml
  app/src/main/res/drawable/ic_user_badge.xml
  app/src/main/res/font/ko_pub_world_dotum_pro_bold.otf
  app/src/main/res/font/ko_pub_world_dotum_pro_light.otf
  app/src/main/res/font/ko_pub_world_dotum_pro_medium.otf
  app/src/main/res/font/outfit_bold.ttf
  app/src/main/res/font/outfit_light.ttf
  app/src/main/res/font/outfit_medium.ttf
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/themes.xml
Labels: ui, day1

#12 스타일 적용
  app/src/main/res/drawable/ic_minus.xml
  app/src/main/res/drawable/ic_minus_mini.xml
  app/src/main/res/drawable/ic_plus.xml
  app/src/main/res/drawable/ic_plus_mini.xml
  app/src/main/res/values/styles.xml
Labels: ui, day1

#17 기획전 UI 화면, 어댑터 생성
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/woowa/banchan/ui/main/MainActivity.kt
  app/src/main/java/com/woowa/banchan/ui/main/MainFragment.kt
  app/src/main/java/com/woowa/banchan/ui/main/Tab.kt
  app/src/main/java/com/woowa/banchan/ui/tabs/ViewPagerAdapter.kt
  app/src/main/java/com/woowa/banchan/ui/tabs/common/BanchanItemAdapter.kt
  app/src/main/java/com/woowa/banchan/ui/tabs/common/BannerAdapter.kt
  app/src/main/java/com/woowa/banchan/ui/tabs/common/MenuDiffUtil.kt
  app/src/main/java/com/woowa/banchan/ui/tabs/home/HomeFragment.kt
  app/src/main/java/com/woowa/banchan/ui/tabs/home/PlanAdapter.kt
  app/src/main/java/com/woowa/banchan/ui/tabs/home/dummyData.kt
  app/src/main/java/com/woowa/banchan/ui/tabs/maindish/MainDishFragment.kt
  app/src/main/java/com/woowa/banchan/ui/tabs/side/SideFragment.kt
  app/src/main/java/com/woowa/banchan/ui/tabs/soup/SoupFragment.kt
  app/src/main/res/drawable/ic_circle_cart.xml
  app/src/main/res/drawable/tab_underline.xml
  app/src/main/res/drawable/tv_background_white_corner_black_15dp.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_main.xml
  app/src/main/res/layout/fragment_maindish.xml
  app/src/main/res/layout/fragment_side.xml
  app/src/main/res/layout/fragment_soup.xml
  app/src/main/res/layout/item_banchan.xml
  app/src/main/res/layout/item_banchan_horizontal.xml
  app/src/main/res/layout/item_banner.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  buildSrc/.gitignore
  buildSrc/src/main/java/Dependencies.kt
  domain/src/main/java/com/woowa/domain/entity/Category.kt
  domain/src/main/java/com/woowa/domain/entity/Menu.kt
Labels: feature, ui, day3

#19 기획전 화면 개선
  app/src/main/java/com/woowa/banchan/ui/tabs/home/HomeFragment.kt
  app/src/main/res/layout/fragment_home.xml
Labels: feature, ui, fix, day3

#24 의존성 주입(Hilt) 적용
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/woowa/banchan/BanchanApplication.kt
  app/src/main/java/com/woowa/banchan/ui/main/MainActivity.kt
  app/src/main/java/com/woowa/banchan/ui/main/MainFragment.kt
  app/src/main/java/com/woowa/banchan/ui/tabs/home/HomeFragment.kt
  app/src/main/java/com/woowa/banchan/ui/tabs/maindish/MainDishFragment.kt
  app/src/main/java/com/woowa/banchan/ui/tabs/side/SideFragment.kt
  app/src/main/java/com/woowa/banchan/ui/tabs/soup/SoupFragment.kt
  build.gradle.kts
  buildSrc/src/main/java/Dependencies.kt
  data/build.gradle.kts
  domain/build.gradle.kts
Labels: chore, day3

#23 시작(스플래시) UI 화면 구현
  app/src/main/AndroidManifest.xml
  app/src/main/ic_launcher-playstore.png
  app/src/main/java/com/woowa/banchan/ui/splash/SplashActivity.kt
  app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  app/src/main/res/drawable/bg_primary_main.xml
  app/src/main/res/drawable/bg_splash_screen.xml
  app/src/main/res/drawable/ic_launcher_foreground.xml
  app/src/main/res/drawable/ic_logo.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values-v31/themes.xml
  app/src/main/res/values/ic_launcher_background.xml
  app/src/main/res/values/themes.xml
Labels: ui, day3

#20 상품 상세 화면 UI 구현
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/woowa/banchan/ui/common/ImageViewBindingAdapter.kt
  app/src/main/java/com/woowa/banchan/ui/common/TextViewBindingAdapter.kt
  app/src/main/java/com/woowa/banchan/ui/detail/DetailFragment.kt
  app/src/main/java/com/woowa/banchan/ui/detail/DetailSectionAdapter.kt
  app/src/main/java/com/woowa/banchan/ui/detail/DetailThumbAdapter.kt
  app/src/main/java/com/woowa/banchan/ui/detail/TestProduct.kt
  app/src/main/java/com/woowa/banchan/ui/main/MainFragment.kt
  app/src/main/java/com/woowa/banchan/ui/tabs/ViewPagerAdapter.kt
  app/src/main/java/com/woowa/banchan/ui/tabs/common/BanchanItemAdapter.kt
  app/src/main/java/com/woowa/banchan/ui/tabs/common/OnClick.kt
  app/src/main/java/com/woowa/banchan/ui/tabs/home/HomeFragment.kt
  app/src/main/java/com/woowa/banchan/ui/tabs/home/PlanAdapter.kt
  app/src/main/java/com/woowa/banchan/utils/MoneyStringConverter.kt
  app/src/main/java/com/woowa/banchan/utils/PixelConverter.kt
  app/src/main/java/com/woowa/banchan/utils/ViewUtil.kt
  app/src/main/res/drawable/btn_circle.xml
  app/src/main/res/drawable/ic_cart.xml
  app/src/main/res/drawable/ic_check.xml
  app/src/main/res/drawable/ic_checkbox.xml
  app/src/main/res/drawable/ic_checkbox_empty.xml
  app/src/main/res/drawable/ic_circle_cart.xml
  app/src/main/res/drawable/ic_close.xml
  app/src/main/res/drawable/ic_down.xml
  app/src/main/res/drawable/ic_grid_selected.xml
  app/src/main/res/drawable/ic_grid_unselected.xml
  app/src/main/res/drawable/ic_launcher_foreground.xml
  app/src/main/res/drawable/ic_left_arrow.xml
  app/src/main/res/drawable/ic_linear_selected.xml
  app/src/main/res/drawable/ic_linear_unselected.xml
  app/src/main/res/drawable/ic_logo.xml
  app/src/main/res/drawable/ic_minus.xml
  app/src/main/res/drawable/ic_minus_mini.xml
  app/src/main/res/drawable/ic_plus.xml
  app/src/main/res/drawable/ic_plus_mini.xml
  app/src/main/res/drawable/ic_reload.xml
  app/src/main/res/drawable/ic_right_arrow.xml
  app/src/main/res/drawable/ic_user.xml
  app/src/main/res/drawable/ic_user_badge.xml
  app/src/main/res/drawable/indicator_round_selected.xml
  app/src/main/res/drawable/indicator_round_unselected.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_detail.xml
  app/src/main/res/layout/item_banchan_horizontal.xml
  app/src/main/res/layout/item_detail_section.xml
  app/src/main/res/layout/item_detail_thumb.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  buildSrc/src/main/java/Dependencies.kt
Labels: feature, ui, fix, day3

#30 멀티 모듈 제거
  app/build.gradle.kts
  app/src/main/java/com/woowa/banchan/domain/entity/Category.kt
  app/src/main/java/com/woowa/banchan/domain/entity/Menu.kt
  app/src/main/java/com/woowa/banchan/ui/tabs/common/BanchanItemAdapter.kt
  app/src/main/java/com/woowa/banchan/ui/tabs/common/MenuDiffUtil.kt
  app/src/main/java/com/woowa/banchan/ui/tabs/home/PlanAdapter.kt
  app/src/main/java/com/woowa/banchan/ui/tabs/home/dummyData.kt
  app/src/main/res/layout/item_banchan.xml
  domain/build.gradle.kts
  domain/src/main/java/com/woowa/domain/MyClass.kt
  settings.gradle.kts
Labels: chore, day4

#31 앱 바 디자인
  app/src/main/java/com/woowa/banchan/ui/common/BanchanAppbar.kt
  app/src/main/res/layout/fragment_detail.xml
  app/src/main/res/layout/fragment_main.xml
  app/src/main/res/layout/view_app_bar.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/themes.xml
Labels: feature, ui, day4

#26 주문 다이얼로그 구현
  app/src/main/java/com/woowa/banchan/ui/tabs/common/BanchanItemAdapter.kt
  app/src/main/java/com/woowa/banchan/ui/tabs/common/CartBottomSheet.kt
  app/src/main/java/com/woowa/banchan/ui/tabs/common/CartDialog.kt
  app/src/main/java/com/woowa/banchan/ui/tabs/home/HomeFragment.kt
  app/src/main/java/com/woowa/banchan/ui/tabs/home/PlanAdapter.kt
  app/src/main/java/com/woowa/banchan/utils/WindowManager.kt
  app/src/main/res/drawable/bg_white_radius_20dp.xml
  app/src/main/res/drawable/bg_white_top_radius_20dp.xml
  app/src/main/res/layout/fragment_bottom_sheet.xml
  app/src/main/res/layout/fragment_dialog.xml
  app/src/main/res/layout/item_banchan.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/values/themes.xml
Labels: feature, ui, day4

#32 API 통신 기초 설정
  app/build.gradle.kts
  app/src/main/java/com/woowa/banchan/data/remote/dto/CategoryDto.kt
  app/src/main/java/com/woowa/banchan/data/remote/dto/DetailProductDto.kt
  app/src/main/java/com/woowa/banchan/data/remote/dto/DetailResponse.kt
  app/src/main/java/com/woowa/banchan/data/remote/dto/ProductDto.kt
  app/src/main/java/com/woowa/banchan/data/remote/dto/SectionResponse.kt
  app/src/main/java/com/woowa/banchan/data/remote/network/BanchanService.kt
  app/src/main/java/com/woowa/banchan/di/RetrofitModule.kt
  build.gradle.kts
  buildSrc/src/main/java/Dependencies.kt
Labels: feature, day4

#33 반찬 API 응답객체 수정
  app/src/main/java/com/woowa/banchan/data/remote/dto/PlanResponse.kt
  app/src/main/java/com/woowa/banchan/data/remote/dto/ProductsResponse.kt
  app/src/main/java/com/woowa/banchan/data/remote/network/BanchanService.kt
Labels: chore, day4

#34 quantitiy 변수 데이터바인딩으로 이동
  app/src/main/java/com/woowa/banchan/ui/tabs/common/CartBottomSheet.kt
  app/src/main/res/layout/fragment_bottom_sheet.xml
  app/src/main/res/layout/fragment_detail.xml
Labels: fix, day4

#35 다이얼로그 데이터바인딩 타입 변경
  app/src/main/res/layout/fragment_bottom_sheet.xml
  app/src/main/res/layout/fragment_detail.xml
Labels: chore, day4

#36 API 요청 테스트 코드 작성
  app/src/main/java/com/woowa/banchan/data/remote/dto/DetailProductDto.kt
  app/src/test/java/com/resources/detail_product.json
  app/src/test/java/com/resources/maindish.json
  app/src/test/java/com/resources/plan.json
  app/src/test/java/com/resources/side.json
  app/src/test/java/com/resources/soup.json
  app/src/test/java/com/woowa/banchan/ExampleUnitTest.kt
  app/src/test/java/com/woowa/banchan/remote/network/BanchanServiceTest.kt
Labels: day4, test

#37 API 호출하는 Remote 데이터 레이어 개발
  app/src/main/java/com/woowa/banchan/data/remote/datasource/BanchanDataSource.kt
  app/src/main/java/com/woowa/banchan/data/remote/datasource/BanchanRemoteDataSource.kt
  app/src/main/java/com/woowa/banchan/data/remote/dto/CategoryDto.kt
  app/src/main/java/com/woowa/banchan/data/remote/dto/DetailResponse.kt
  app/src/main/java/com/woowa/banchan/data/remote/dto/ProductDto.kt
  app/src/main/java/com/woowa/banchan/data/remote/network/BanchanService.kt
  app/src/main/java/com/woowa/banchan/data/remote/repository/BanchanRepositoryImpl.kt
  app/src/main/java/com/woowa/banchan/di/DataSourceModule.kt
  app/src/main/java/com/woowa/banchan/di/RepositoryModule.kt
  app/src/main/java/com/woowa/banchan/domain/entity/Category.kt
  app/src/main/java/com/woowa/banchan/domain/entity/DetailProduct.kt
  app/src/main/java/com/woowa/banchan/domain/entity/Product.kt
  app/src/main/java/com/woowa/banchan/domain/exception/NotFoundProductsException.kt
  app/src/main/java/com/woowa/banchan/domain/repository/BanchanRepository.kt
  app/src/main/java/com/woowa/banchan/ui/tabs/common/BanchanItemAdapter.kt
  app/src/main/java/com/woowa/banchan/ui/tabs/common/MenuDiffUtil.kt
  app/src/main/java/com/woowa/banchan/ui/tabs/home/dummyData.kt
  app/src/main/res/layout/item_banchan.xml
  app/src/test/java/com/woowa/banchan/data/remote/repository/BanchanRepositoryImplTest.kt
  app/src/test/java/com/woowa/banchan/remote/network/BanchanServiceTest.kt
Labels: refactor, day4, test

#38 repository 테스트 코드 추가
  app/src/test/java/com/woowa/banchan/data/remote/repository/BanchanRepositoryImplTest.kt
  app/src/test/java/com/woowa/banchan/data/remote/repository/FakeDataSource.kt
Labels: feature, day4

#40 기획전 데이터와 UI 화면 연결
  app/build.gradle.kts
  app/src/main/java/com/woowa/banchan/data/remote/dto/ProductDto.kt
  app/src/main/java/com/woowa/banchan/di/RetrofitModule.kt
  app/src/main/java/com/woowa/banchan/di/UseCaseModule.kt
  app/src/main/java/com/woowa/banchan/domain/entity/Product.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/GetPlanUseCase.kt
  app/src/main/java/com/woowa/banchan/ui/common/ImageViewBindingAdapter.kt
  app/src/main/java/com/woowa/banchan/ui/tabs/common/BanchanItemAdapter.kt
  app/src/main/java/com/woowa/banchan/ui/tabs/common/CartBottomSheet.kt
  app/src/main/java/com/woowa/banchan/ui/tabs/home/HomeFragment.kt
  app/src/main/java/com/woowa/banchan/ui/tabs/home/PlanAdapter.kt
  app/src/main/java/com/woowa/banchan/ui/tabs/home/PlanUiState.kt
  app/src/main/java/com/woowa/banchan/ui/tabs/home/PlanViewModel.kt
  app/src/main/res/drawable-v23/iv_placeholder.xml
  app/src/main/res/drawable/iv_placeholder.xml
  app/src/main/res/layout/fragment_bottom_sheet.xml
  app/src/main/res/layout/item_banchan.xml
  app/src/main/res/layout/item_banchan_horizontal.xml
  buildSrc/src/main/java/Dependencies.kt
Labels: feature, ui, day5

#42 상품 상세 데이터와 UI 화면 연결
  app/src/main/java/com/woowa/banchan/di/UseCaseModule.kt
  app/src/main/java/com/woowa/banchan/domain/entity/DetailProduct.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/GetDetailProductUseCase.kt
  app/src/main/java/com/woowa/banchan/ui/common/TextViewBindingAdapter.kt
  app/src/main/java/com/woowa/banchan/ui/detail/DetailFragment.kt
  app/src/main/java/com/woowa/banchan/ui/detail/DetailUiState.kt
  app/src/main/java/com/woowa/banchan/ui/detail/DetailViewModel.kt
  app/src/main/java/com/woowa/banchan/ui/main/MainFragment.kt
  app/src/main/java/com/woowa/banchan/ui/tabs/common/BanchanItemAdapter.kt
  app/src/main/java/com/woowa/banchan/ui/tabs/common/OnClick.kt
  app/src/main/java/com/woowa/banchan/ui/tabs/home/HomeFragment.kt
  app/src/main/java/com/woowa/banchan/ui/tabs/home/PlanAdapter.kt
  app/src/main/res/layout/fragment_detail.xml
Labels: feature, ui, fix, day5

#45 홈 화면 스크롤 중첩 문제 해결
  app/src/main/java/com/woowa/banchan/ui/tabs/common/HorizontalScrollListener.kt
  app/src/main/java/com/woowa/banchan/ui/tabs/home/PlanAdapter.kt
Labels: fix, day6

#46 화면 전환 시 프래그먼트 전환 객체를 보존하지 않는 문제 해결
  app/src/main/java/com/woowa/banchan/ui/main/MainFragment.kt
  app/src/main/java/com/woowa/banchan/ui/tabs/ViewPagerAdapter.kt
  app/src/main/java/com/woowa/banchan/ui/tabs/common/OnClick.kt
  app/src/main/java/com/woowa/banchan/ui/tabs/home/HomeFragment.kt
Labels: fix, day6

#48 홈 화면이 재생성될 때마다 동일한 화면이 아래에 추가되는 문제 해결
  app/src/main/java/com/woowa/banchan/ui/detail/DetailFragment.kt
  app/src/main/java/com/woowa/banchan/ui/tabs/home/HomeFragment.kt
Labels: fix, day7

#50 존재하지 않는 객체 사용으로 컴파일 에러 발생 문제
  app/src/main/java/com/woowa/banchan/ui/tabs/home/HomeFragment.kt
Labels: fix, day7

#54 장바구니 화면 ui 구성
  app/build.gradle.kts
  app/src/main/java/com/woowa/banchan/ui/cart/CartFragment.kt
  app/src/main/java/com/woowa/banchan/ui/cart/CartScreen.kt
  app/src/main/java/com/woowa/banchan/ui/cart/CartUiState.kt
  app/src/main/java/com/woowa/banchan/ui/cart/CartViewModel.kt
  app/src/main/java/com/woowa/banchan/ui/cart/TestCart.kt
  app/src/main/java/com/woowa/banchan/ui/cart/TestRecently.kt
  app/src/main/java/com/woowa/banchan/ui/cart/components/CartCheckBox.kt
  app/src/main/java/com/woowa/banchan/ui/cart/components/CartColumn.kt
  app/src/main/java/com/woowa/banchan/ui/cart/components/CartItemRow.kt
  app/src/main/java/com/woowa/banchan/ui/cart/components/CartPriceColumn.kt
  app/src/main/java/com/woowa/banchan/ui/cart/components/CheckState.kt
  app/src/main/java/com/woowa/banchan/ui/cart/components/GlideImage.kt
  app/src/main/java/com/woowa/banchan/ui/cart/components/RecentlyViewedColumn.kt
  app/src/main/java/com/woowa/banchan/ui/common/BanchanAppbar.kt
  app/src/main/java/com/woowa/banchan/ui/common/BanchanAppbarBindingAdapter.kt
  app/src/main/java/com/woowa/banchan/ui/common/OnBackClickListener.kt
  app/src/main/java/com/woowa/banchan/ui/common/OnCartClickListener.kt
  app/src/main/java/com/woowa/banchan/ui/detail/DetailFragment.kt
  app/src/main/java/com/woowa/banchan/ui/main/MainActivity.kt
  app/src/main/java/com/woowa/banchan/ui/main/MainFragment.kt
  app/src/main/java/com/woowa/banchan/utils/SubstringConverter.kt
  app/src/main/res/drawable/ic_minus_mini.xml
  app/src/main/res/drawable/ic_plus_mini.xml
  app/src/main/res/layout/fragment_cart.xml
  app/src/main/res/layout/fragment_detail.xml
  app/src/main/res/layout/fragment_main.xml
  app/src/main/res/layout/view_app_bar.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  buildSrc/src/main/java/Dependencies.kt
Labels: feature, ui, chore, day8

#58 장바구니 Compose 코드 피드백 반영
  app/src/main/java/com/woowa/banchan/extensions/SubstringConverter.kt
  app/src/main/java/com/woowa/banchan/extensions/TimeStringConverter.kt
  app/src/main/java/com/woowa/banchan/ui/cart/components/RecentlyViewedColumn.kt
Labels: feature, refactor, day9

#59 총 상품 갯수, 정렬 어댑터 생성
  app/src/main/java/com/woowa/banchan/ui/main/tabs/adapter/CountFilterAdapter.kt
  app/src/main/res/layout/item_count_filter.xml
  app/src/main/res/values/strings.xml
Labels: feature, day9

#66 앱바의 카트 개수와 주문내역 알림 UI 구현
  app/src/main/java/com/woowa/banchan/ui/bindingadapter/BanchanAppbarBindingAdapter.kt
  app/src/main/java/com/woowa/banchan/ui/customview/BanchanAppbar.kt
  app/src/main/java/com/woowa/banchan/ui/main/MainFragment.kt
  app/src/main/res/drawable/bg_black_circle.xml
  app/src/main/res/layout/fragment_main.xml
  app/src/main/res/layout/view_app_bar.xml
Labels: ui, day10

#67 정갈한 밑반찬 로직
  app/src/main/java/com/woowa/banchan/ui/main/tabs/side/SideFragment.kt
  app/src/main/res/layout/fragment_side.xml
Labels: feature, ui, day10

#64 뜨끈한 국물 요리 로직 완성
  app/src/main/java/com/woowa/banchan/domain/entity/ProductViewType.kt
  app/src/main/java/com/woowa/banchan/ui/bindingadapter/BanchanAppbarBindingAdapter.kt
  app/src/main/java/com/woowa/banchan/ui/customview/BanchanAppbar.kt
  app/src/main/java/com/woowa/banchan/ui/main/MainFragment.kt
  app/src/main/java/com/woowa/banchan/ui/main/tabs/adapter/CountFilterAdapter.kt
  app/src/main/java/com/woowa/banchan/ui/main/tabs/adapter/ProductAdapter.kt
  app/src/main/java/com/woowa/banchan/ui/main/tabs/decoration/ItemDecoration.kt
  app/src/main/java/com/woowa/banchan/ui/main/tabs/home/PlanAdapter.kt
  app/src/main/java/com/woowa/banchan/ui/main/tabs/maindish/MainDishFragment.kt
  app/src/main/java/com/woowa/banchan/ui/main/tabs/side/SideFragment.kt
  app/src/main/java/com/woowa/banchan/ui/main/tabs/soup/SoupFragment.kt
  app/src/main/res/drawable/bg_black_circle.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_main.xml
  app/src/main/res/layout/fragment_maindish.xml
  app/src/main/res/layout/fragment_side.xml
  app/src/main/res/layout/fragment_soup.xml
  app/src/main/res/layout/item_banchan_grid.xml
  app/src/main/res/layout/item_banchan_horizontal.xml
  app/src/main/res/layout/item_banchan_plan.xml
  app/src/main/res/layout/item_count_filter.xml
  app/src/main/res/layout/item_spinner_title.xml
  app/src/main/res/layout/item_type_filter.xml
  app/src/main/res/layout/view_app_bar.xml
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/strings.xml
Labels: feature, ui, day10

#71 데이터베이스 기초 설정
  app/build.gradle.kts
  app/src/main/java/com/woowa/banchan/data/local/dao/CartDao.kt
  app/src/main/java/com/woowa/banchan/data/local/dao/OrderDao.kt
  app/src/main/java/com/woowa/banchan/data/local/dao/RecentlyViewedDao.kt
  app/src/main/java/com/woowa/banchan/data/local/database/AppDatabase.kt
  app/src/main/java/com/woowa/banchan/data/local/entity/CartEntity.kt
  app/src/main/java/com/woowa/banchan/data/local/entity/OrderEntity.kt
  app/src/main/java/com/woowa/banchan/data/local/entity/OrderLineItemEntity.kt
  app/src/main/java/com/woowa/banchan/data/local/entity/RecentlyViewedEntity.kt
  app/src/main/java/com/woowa/banchan/di/DatabaseModule.kt
  buildSrc/src/main/java/Dependencies.kt
Labels: chore, day10

#73 CartDao 테스트 코드 작성
  app/build.gradle.kts
  app/src/androidTest/java/com/woowa/banchan/data/local/CartDaoTest.kt
  app/src/main/java/com/woowa/banchan/data/local/dao/CartDao.kt
Labels: test, day10

#75 RecentlyViewedDao 테스트코드 작성
  app/src/androidTest/java/com/woowa/banchan/data/local/RecentlyViewedDaoTest.kt
  app/src/main/java/com/woowa/banchan/data/local/dao/RecentlyViewedDao.kt
Labels: test, day10

#77 OrderDao 테스트코드 작성
  app/build.gradle.kts
  app/src/androidTest/java/com/woowa/banchan/data/local/CartDaoTest.kt
  app/src/androidTest/java/com/woowa/banchan/data/local/OrderDaoTest.kt
  app/src/androidTest/java/com/woowa/banchan/data/local/RecentlyViewedDaoTest.kt
  app/src/main/java/com/woowa/banchan/data/local/dao/CartDao.kt
  app/src/main/java/com/woowa/banchan/data/local/dao/OrderDao.kt
  app/src/main/java/com/woowa/banchan/data/local/dao/RecentlyViewedDao.kt
  app/src/main/java/com/woowa/banchan/data/local/database/AppDatabase.kt
  app/src/main/java/com/woowa/banchan/data/local/entity/OrderLineItemView.kt
Labels: feature, test, day11

#84 데이터베이스와 최근 본 상품 화면 연결
  app/src/androidTest/java/com/woowa/banchan/data/local/FakeRecentlyViewedDataSource.kt
  app/src/androidTest/java/com/woowa/banchan/data/local/RecentlyViewedDaoTest.kt
  app/src/androidTest/java/com/woowa/banchan/data/local/RecentlyViewedRepositoryTest.kt
  app/src/main/java/com/woowa/banchan/data/local/dao/RecentlyViewedDao.kt
  app/src/main/java/com/woowa/banchan/data/local/database/AppDatabase.kt
  app/src/main/java/com/woowa/banchan/data/local/datasource/RecentlyViewedDataSource.kt
  app/src/main/java/com/woowa/banchan/data/local/datasource/RecentlyViewedDataSourceImpl.kt
  app/src/main/java/com/woowa/banchan/data/local/entity/RecentlyViewedEntity.kt
  app/src/main/java/com/woowa/banchan/data/local/repository/RecentlyViewedRepositoryImpl.kt
  app/src/main/java/com/woowa/banchan/di/DataSourceModule.kt
  app/src/main/java/com/woowa/banchan/di/RepositoryModule.kt
  app/src/main/java/com/woowa/banchan/di/UseCaseModule.kt
  app/src/main/java/com/woowa/banchan/domain/entity/RecentlyViewed.kt
  app/src/main/java/com/woowa/banchan/domain/repository/RecentlyViewedRepository.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/GetAllRecentlyViewedUseCase.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/ModifyRecentlyViewedUseCase.kt
  app/src/main/java/com/woowa/banchan/extensions/TimeStringConverter.kt
  app/src/main/java/com/woowa/banchan/ui/cart/CartFragment.kt
  app/src/main/java/com/woowa/banchan/ui/cart/CartScreen.kt
  app/src/main/java/com/woowa/banchan/ui/cart/CartUiState.kt
  app/src/main/java/com/woowa/banchan/ui/cart/CartViewModel.kt
  app/src/main/java/com/woowa/banchan/ui/cart/components/RecentlyViewedColumn.kt
  app/src/main/java/com/woowa/banchan/ui/main/tabs/home/HomeFragment.kt
  app/src/main/java/com/woowa/banchan/ui/main/tabs/maindish/MainDishFragment.kt
  app/src/main/java/com/woowa/banchan/ui/main/tabs/side/SideFragment.kt
  app/src/main/java/com/woowa/banchan/ui/main/tabs/soup/SoupFragment.kt
  app/src/main/java/com/woowa/banchan/ui/recently/RecentlyAdapter.kt
  app/src/main/java/com/woowa/banchan/ui/recently/RecentlyFragment.kt
  app/src/main/java/com/woowa/banchan/ui/recently/RecentlyUiState.kt
  app/src/main/java/com/woowa/banchan/ui/recently/RecentlyViewModel.kt
  app/src/main/java/com/woowa/banchan/ui/recently/TestRecently.kt
  app/src/main/res/layout/item_recently.xml
Labels: feature, ui, fix, test, day12

#85 최근 본 상품 & 장바구니 일부 기능 추가 및 디자인 변경
  app/src/androidTest/java/com/woowa/banchan/data/local/RecentlyViewedDaoTest.kt
  app/src/main/java/com/woowa/banchan/domain/entity/RecentlyViewed.kt
  app/src/main/java/com/woowa/banchan/ui/cart/CartFragment.kt
  app/src/main/java/com/woowa/banchan/ui/cart/CartScreen.kt
  app/src/main/java/com/woowa/banchan/ui/cart/components/CartColumn.kt
  app/src/main/java/com/woowa/banchan/ui/cart/components/CartPriceColumn.kt
  app/src/main/java/com/woowa/banchan/ui/cart/components/RecentlyViewedColumn.kt
  app/src/main/java/com/woowa/banchan/ui/recently/RecentlyFragment.kt
Labels: feature, ui, day12

#86 최근 본 상품 flow에게 강제로 발행을 요청하지 않아도 흐름에 따라 발행되도록 함
  app/src/androidTest/java/com/woowa/banchan/data/local/FakeRecentlyViewedDataSource.kt
  app/src/main/java/com/woowa/banchan/data/local/repository/RecentlyViewedRepositoryImpl.kt
  app/src/main/java/com/woowa/banchan/ui/cart/CartFragment.kt
  app/src/main/java/com/woowa/banchan/ui/recently/RecentlyViewModel.kt
Labels: feature, refactor, day13

#95 탭 상품 조회 유스케이스 개선
  app/src/main/java/com/woowa/banchan/domain/entity/Product.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/GetPlanUseCase.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/GetProductsUseCase.kt
  app/src/main/java/com/woowa/banchan/ui/main/tabs/home/PlanAdapter.kt
  app/src/main/java/com/woowa/banchan/ui/main/tabs/maindish/MainDishFragment.kt
  app/src/main/java/com/woowa/banchan/ui/main/tabs/side/SideFragment.kt
  app/src/main/java/com/woowa/banchan/ui/main/tabs/soup/SoupFragment.kt
  app/src/main/res/drawable/ic_circle_in_cart.xml
  app/src/main/res/layout/item_banchan_grid.xml
  app/src/main/res/layout/item_banchan_horizontal.xml
  app/src/main/res/layout/item_banchan_vertical.xml
Labels: feature, day13

#93 상품 상세화면에서 주문 담기 기능 구현
  app/src/main/java/com/woowa/banchan/domain/entity/Product.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/GetDetailProductUseCase.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/GetPlanUseCase.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/GetProductsUseCase.kt
  app/src/main/java/com/woowa/banchan/ui/detail/DetailFragment.kt
  app/src/main/java/com/woowa/banchan/ui/main/tabs/home/PlanAdapter.kt
  app/src/main/java/com/woowa/banchan/ui/main/tabs/maindish/MainDishFragment.kt
  app/src/main/java/com/woowa/banchan/ui/main/tabs/side/SideFragment.kt
  app/src/main/java/com/woowa/banchan/ui/main/tabs/soup/SoupFragment.kt
  app/src/main/res/drawable/ic_circle_in_cart.xml
  app/src/main/res/layout/item_banchan_grid.xml
  app/src/main/res/layout/item_banchan_horizontal.xml
  app/src/main/res/layout/item_banchan_vertical.xml
Labels: feature, day13

#92 장바구니 삭제 유스케이스 생성
  app/src/main/java/com/woowa/banchan/data/local/repository/RecentlyViewedRepositoryImpl.kt
  app/src/main/java/com/woowa/banchan/di/UseCaseModule.kt
  app/src/main/java/com/woowa/banchan/domain/entity/Product.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/GetDetailProductUseCase.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/GetPlanUseCase.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/GetProductsUseCase.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/cart/RemoveCartUseCase.kt
  app/src/main/java/com/woowa/banchan/ui/cart/CartFragment.kt
  app/src/main/java/com/woowa/banchan/ui/cart/CartViewModel.kt
  app/src/main/java/com/woowa/banchan/ui/cart/components/CartCheckBox.kt
  app/src/main/java/com/woowa/banchan/ui/customview/CartBottomSheet.kt
  app/src/main/java/com/woowa/banchan/ui/customview/CartDialog.kt
  app/src/main/java/com/woowa/banchan/ui/detail/DetailFragment.kt
  app/src/main/java/com/woowa/banchan/ui/detail/DetailViewModel.kt
  app/src/main/java/com/woowa/banchan/ui/main/tabs/home/HomeFragment.kt
  app/src/main/java/com/woowa/banchan/ui/main/tabs/home/PlanAdapter.kt
  app/src/main/java/com/woowa/banchan/ui/main/tabs/maindish/MainDishFragment.kt
  app/src/main/java/com/woowa/banchan/ui/main/tabs/side/SideFragment.kt
  app/src/main/java/com/woowa/banchan/ui/main/tabs/soup/SoupFragment.kt
  app/src/main/res/drawable/ic_circle_in_cart.xml
  app/src/main/res/layout/fragment_bottom_sheet.xml
  app/src/main/res/layout/fragment_detail.xml
  app/src/main/res/layout/fragment_dialog.xml
  app/src/main/res/layout/item_banchan_grid.xml
  app/src/main/res/layout/item_banchan_horizontal.xml
  app/src/main/res/layout/item_banchan_vertical.xml
Labels: feature, day12

#90 장바구니 추가 유스케이스 개선
  app/src/androidTest/java/com/woowa/banchan/data/local/CartDaoTest.kt
  app/src/main/java/com/woowa/banchan/data/local/dao/CartDao.kt
  app/src/main/java/com/woowa/banchan/data/local/datasource/CartDataSource.kt
  app/src/main/java/com/woowa/banchan/data/local/datasource/CartLocalDataSource.kt
  app/src/main/java/com/woowa/banchan/data/local/repository/CartRepositoryImpl.kt
  app/src/main/java/com/woowa/banchan/data/local/repository/RecentlyViewedRepositoryImpl.kt
  app/src/main/java/com/woowa/banchan/di/UseCaseModule.kt
  app/src/main/java/com/woowa/banchan/domain/entity/Product.kt
  app/src/main/java/com/woowa/banchan/domain/exception/ExistCartException.kt
  app/src/main/java/com/woowa/banchan/domain/repository/CartRepository.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/GetDetailProductUseCase.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/GetPlanUseCase.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/GetProductsUseCase.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/cart/AddCartUseCase.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/cart/ExistCartUseCase.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/cart/GetCartUseCase.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/cart/GetCartWithHashUseCase.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/cart/ModifyCartUseCase.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/cart/RemoveCartUseCase.kt
  app/src/main/java/com/woowa/banchan/ui/cart/CartFragment.kt
  app/src/main/java/com/woowa/banchan/ui/cart/CartViewModel.kt
  app/src/main/java/com/woowa/banchan/ui/cart/components/CartCheckBox.kt
  app/src/main/java/com/woowa/banchan/ui/customview/CartBottomSheet.kt
  app/src/main/java/com/woowa/banchan/ui/customview/CartDialog.kt
  app/src/main/java/com/woowa/banchan/ui/detail/DetailFragment.kt
  app/src/main/java/com/woowa/banchan/ui/detail/DetailViewModel.kt
  app/src/main/java/com/woowa/banchan/ui/main/tabs/adapter/ProductAdapter.kt
  app/src/main/java/com/woowa/banchan/ui/main/tabs/adapter/ProductDiffUtil.kt
  app/src/main/java/com/woowa/banchan/ui/main/tabs/home/HomeFragment.kt
  app/src/main/java/com/woowa/banchan/ui/main/tabs/home/PlanAdapter.kt
  app/src/main/java/com/woowa/banchan/ui/main/tabs/maindish/MainDishFragment.kt
  app/src/main/java/com/woowa/banchan/ui/main/tabs/side/SideFragment.kt
  app/src/main/java/com/woowa/banchan/ui/main/tabs/soup/SoupFragment.kt
  app/src/main/res/drawable/ic_circle_in_cart.xml
  app/src/main/res/layout/fragment_bottom_sheet.xml
  app/src/main/res/layout/fragment_detail.xml
  app/src/main/res/layout/fragment_dialog.xml
  app/src/main/res/layout/item_banchan_grid.xml
  app/src/main/res/layout/item_banchan_horizontal.xml
  app/src/main/res/layout/item_banchan_vertical.xml
Labels: feature, day12

#88 장바구니 추가 유스케이스 생성
  app/src/androidTest/java/com/woowa/banchan/data/local/CartDaoTest.kt
  app/src/main/java/com/woowa/banchan/data/local/dao/CartDao.kt
  app/src/main/java/com/woowa/banchan/data/local/datasource/CartDataSource.kt
  app/src/main/java/com/woowa/banchan/data/local/datasource/CartLocalDataSource.kt
  app/src/main/java/com/woowa/banchan/data/local/entity/CartEntity.kt
  app/src/main/java/com/woowa/banchan/data/local/repository/CartRepositoryImpl.kt
  app/src/main/java/com/woowa/banchan/data/local/repository/RecentlyViewedRepositoryImpl.kt
  app/src/main/java/com/woowa/banchan/di/DataSourceModule.kt
  app/src/main/java/com/woowa/banchan/di/DatabaseModule.kt
  app/src/main/java/com/woowa/banchan/di/RepositoryModule.kt
  app/src/main/java/com/woowa/banchan/di/UseCaseModule.kt
  app/src/main/java/com/woowa/banchan/domain/entity/Cart.kt
  app/src/main/java/com/woowa/banchan/domain/entity/Product.kt
  app/src/main/java/com/woowa/banchan/domain/repository/CartRepository.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/GetDetailProductUseCase.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/GetPlanUseCase.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/GetProductsUseCase.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/cart/AddCartUseCase.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/cart/ExistCartUseCase.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/cart/GetCartUseCase.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/cart/GetCartWithHashUseCase.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/cart/ModifyCartUseCase.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/cart/RemoveCartUseCase.kt
  app/src/main/java/com/woowa/banchan/extensions/TimeStringConverter.kt
  app/src/main/java/com/woowa/banchan/ui/cart/CartFragment.kt
  app/src/main/java/com/woowa/banchan/ui/cart/CartScreen.kt
  app/src/main/java/com/woowa/banchan/ui/cart/CartUiState.kt
  app/src/main/java/com/woowa/banchan/ui/cart/CartViewModel.kt
  app/src/main/java/com/woowa/banchan/ui/cart/TestCart.kt
  app/src/main/java/com/woowa/banchan/ui/cart/components/CartCheckBox.kt
  app/src/main/java/com/woowa/banchan/ui/cart/components/CartColumn.kt
  app/src/main/java/com/woowa/banchan/ui/cart/components/CartItemRow.kt
  app/src/main/java/com/woowa/banchan/ui/cart/components/CartPriceColumn.kt
  app/src/main/java/com/woowa/banchan/ui/customview/CartBottomSheet.kt
  app/src/main/java/com/woowa/banchan/ui/customview/CartDialog.kt
  app/src/main/java/com/woowa/banchan/ui/detail/DetailFragment.kt
  app/src/main/java/com/woowa/banchan/ui/detail/DetailViewModel.kt
  app/src/main/java/com/woowa/banchan/ui/main/MainFragment.kt
  app/src/main/java/com/woowa/banchan/ui/main/tabs/adapter/ProductAdapter.kt
  app/src/main/java/com/woowa/banchan/ui/main/tabs/adapter/ProductDiffUtil.kt
  app/src/main/java/com/woowa/banchan/ui/main/tabs/decoration/ItemDecoration.kt
  app/src/main/java/com/woowa/banchan/ui/main/tabs/home/HomeFragment.kt
  app/src/main/java/com/woowa/banchan/ui/main/tabs/home/PlanAdapter.kt
  app/src/main/java/com/woowa/banchan/ui/main/tabs/maindish/MainDishFragment.kt
  app/src/main/java/com/woowa/banchan/ui/main/tabs/side/SideFragment.kt
  app/src/main/java/com/woowa/banchan/ui/main/tabs/soup/SoupFragment.kt
  app/src/main/res/drawable/ic_circle_in_cart.xml
  app/src/main/res/layout/fragment_bottom_sheet.xml
  app/src/main/res/layout/fragment_detail.xml
  app/src/main/res/layout/fragment_dialog.xml
  app/src/main/res/layout/item_banchan_grid.xml
  app/src/main/res/layout/item_banchan_horizontal.xml
  app/src/main/res/layout/item_banchan_vertical.xml
Labels: feature, day12

#96 주문 화면 data / domain layer 구현
  app/src/main/java/com/woowa/banchan/data/local/dao/OrderDao.kt
  app/src/main/java/com/woowa/banchan/data/local/database/AppDatabase.kt
  app/src/main/java/com/woowa/banchan/data/local/datasource/OrderDataSource.kt
  app/src/main/java/com/woowa/banchan/data/local/datasource/OrderDataSourceImpl.kt
  app/src/main/java/com/woowa/banchan/data/local/entity/OrderEntity.kt
  app/src/main/java/com/woowa/banchan/data/local/entity/OrderLineItemEntity.kt
  app/src/main/java/com/woowa/banchan/data/local/entity/OrderLineItemView.kt
  app/src/main/java/com/woowa/banchan/data/local/repository/OrderRepositoryImpl.kt
  app/src/main/java/com/woowa/banchan/di/DataSourceModule.kt
  app/src/main/java/com/woowa/banchan/di/RepositoryModule.kt
  app/src/main/java/com/woowa/banchan/domain/entity/Order.kt
  app/src/main/java/com/woowa/banchan/domain/entity/OrderLineItem.kt
  app/src/main/java/com/woowa/banchan/domain/repository/OrderRepository.kt
Labels: feature, day14

#99 장바구니 화면 일부 버그 수정
  app/src/main/java/com/woowa/banchan/ui/cart/CartFragment.kt
  app/src/main/java/com/woowa/banchan/ui/cart/CartScreen.kt
  app/src/main/java/com/woowa/banchan/ui/cart/CartViewModel.kt
  app/src/main/java/com/woowa/banchan/ui/cart/TestCart.kt
  app/src/main/java/com/woowa/banchan/ui/cart/components/CartColumn.kt
  app/src/main/java/com/woowa/banchan/ui/cart/components/CartItemRow.kt
  app/src/main/java/com/woowa/banchan/ui/customview/CartDialog.kt
  app/src/main/java/com/woowa/banchan/ui/detail/DetailFragment.kt
  app/src/main/java/com/woowa/banchan/ui/main/MainFragment.kt
  app/src/main/java/com/woowa/banchan/ui/recently/RecentlyFragment.kt
  app/src/main/java/com/woowa/banchan/ui/recently/RecentlyViewModel.kt
  app/src/main/res/anim/slide_in.xml
  app/src/main/res/anim/slide_out.xml
  app/src/main/res/layout/fragment_recently.xml
Labels: ui, fix, day14

#100 주문 상세화면 UI 구현
  app/src/main/java/com/woowa/banchan/data/local/entity/OrderEntity.kt
  app/src/main/java/com/woowa/banchan/data/local/entity/OrderLineItemEntity.kt
  app/src/main/java/com/woowa/banchan/data/local/entity/OrderLineItemView.kt
  app/src/main/java/com/woowa/banchan/data/local/repository/OrderRepositoryImpl.kt
  app/src/main/java/com/woowa/banchan/domain/entity/Order.kt
  app/src/main/java/com/woowa/banchan/domain/entity/OrderDetailSection.kt
  app/src/main/java/com/woowa/banchan/domain/entity/OrderLineItem.kt
  app/src/main/java/com/woowa/banchan/domain/repository/OrderRepository.kt
  app/src/main/java/com/woowa/banchan/extensions/TimeStringConverter.kt
  app/src/main/java/com/woowa/banchan/ui/OnOrderClickListener.kt
  app/src/main/java/com/woowa/banchan/ui/bindingadapter/TextViewBindingAdapter.kt
  app/src/main/java/com/woowa/banchan/ui/cart/components/CartPriceColumn.kt
  app/src/main/java/com/woowa/banchan/ui/main/MainFragment.kt
  app/src/main/java/com/woowa/banchan/ui/orderdetail/OrderDetailAdapter.kt
  app/src/main/java/com/woowa/banchan/ui/orderdetail/OrderDetailFragment.kt
  app/src/main/res/layout/fragment_main.xml
  app/src/main/res/layout/fragment_order_detail.xml
  app/src/main/res/layout/item_order_detail.xml
  app/src/main/res/layout/item_order_detail_footer.xml
  app/src/main/res/layout/item_order_detail_header.xml
  app/src/main/res/values/strings.xml
Labels: feature, ui, day13

#101 주문 상세화면에 사용될 뷰모델, 유스케이스 생성
  app/src/main/java/com/woowa/banchan/data/local/dao/OrderDao.kt
  app/src/main/java/com/woowa/banchan/data/local/datasource/OrderDataSource.kt
  app/src/main/java/com/woowa/banchan/data/local/datasource/OrderDataSourceImpl.kt
  app/src/main/java/com/woowa/banchan/data/local/entity/OrderLineItemEntity.kt
  app/src/main/java/com/woowa/banchan/data/local/repository/OrderRepositoryImpl.kt
  app/src/main/java/com/woowa/banchan/di/UseCaseModule.kt
  app/src/main/java/com/woowa/banchan/domain/exception/NotUpdateException.kt
  app/src/main/java/com/woowa/banchan/domain/repository/OrderRepository.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/order/GetOrderLineItemUseCase.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/order/ModifyOrderUseCase.kt
  app/src/main/java/com/woowa/banchan/ui/orderdetail/OrderDetailFragment.kt
  app/src/main/java/com/woowa/banchan/ui/orderdetail/OrderDetailViewModel.kt
  app/src/main/java/com/woowa/banchan/ui/orderdetail/OrderLineItemUiState.kt
  app/src/main/res/layout/fragment_order_detail.xml
  app/src/main/res/layout/item_order_detail.xml
  app/src/main/res/layout/item_order_detail_header.xml
Labels: feature, day14

#102 주문 내역 화면 ui layer 결합
  app/src/main/java/com/woowa/banchan/BanchanApplication.kt
  app/src/main/java/com/woowa/banchan/data/local/dao/OrderDao.kt
  app/src/main/java/com/woowa/banchan/data/local/database/AppDatabase.kt
  app/src/main/java/com/woowa/banchan/data/local/datasource/OrderDataSource.kt
  app/src/main/java/com/woowa/banchan/data/local/datasource/OrderDataSourceImpl.kt
  app/src/main/java/com/woowa/banchan/data/local/entity/OrderInfoView.kt
  app/src/main/java/com/woowa/banchan/data/local/entity/OrderLineItemEntity.kt
  app/src/main/java/com/woowa/banchan/data/local/entity/OrderLineItemView.kt
  app/src/main/java/com/woowa/banchan/data/local/repository/OrderRepositoryImpl.kt
  app/src/main/java/com/woowa/banchan/di/UseCaseModule.kt
  app/src/main/java/com/woowa/banchan/domain/entity/OrderInfo.kt
  app/src/main/java/com/woowa/banchan/domain/repository/OrderRepository.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/order/AddOrderUserCase.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/order/GetOrderInfoUseCase.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/order/GetOrderLineItemUseCase.kt
  app/src/main/java/com/woowa/banchan/ui/OnOrderClickListener.kt
  app/src/main/java/com/woowa/banchan/ui/OnOrderDetailClickListener.kt
  app/src/main/java/com/woowa/banchan/ui/bindingadapter/TextViewBindingAdapter.kt
  app/src/main/java/com/woowa/banchan/ui/cart/CartFragment.kt
  app/src/main/java/com/woowa/banchan/ui/cart/CartScreen.kt
  app/src/main/java/com/woowa/banchan/ui/cart/CartViewModel.kt
  app/src/main/java/com/woowa/banchan/ui/cart/components/CartColumn.kt
  app/src/main/java/com/woowa/banchan/ui/customview/CartDialog.kt
  app/src/main/java/com/woowa/banchan/ui/detail/DetailFragment.kt
  app/src/main/java/com/woowa/banchan/ui/detail/TestProduct.kt
  app/src/main/java/com/woowa/banchan/ui/main/MainFragment.kt
  app/src/main/java/com/woowa/banchan/ui/order/OrderFragment.kt
  app/src/main/java/com/woowa/banchan/ui/order/OrderListAdapter.kt
  app/src/main/java/com/woowa/banchan/ui/order/OrderUiState.kt
  app/src/main/java/com/woowa/banchan/ui/order/OrderViewModel.kt
  app/src/main/java/com/woowa/banchan/ui/orderdetail/OrderDetailAdapter.kt
  app/src/main/java/com/woowa/banchan/ui/orderdetail/OrderDetailFragment.kt
  app/src/main/java/com/woowa/banchan/ui/orderdetail/OrderDetailViewModel.kt
  app/src/main/java/com/woowa/banchan/ui/recently/RecentlyFragment.kt
  app/src/main/res/layout/fragment_main.xml
  app/src/main/res/layout/fragment_order.xml
  app/src/main/res/layout/item_order.xml
  app/src/main/res/values/strings.xml
Labels: feature, ui, refactor, day14

#114 배달 상태 enum class 생성
  app/build.gradle.kts
  app/src/main/java/com/woowa/banchan/data/local/entity/OrderEntity.kt
  app/src/main/java/com/woowa/banchan/data/local/entity/OrderLineItemView.kt
  app/src/main/java/com/woowa/banchan/domain/entity/DeliveryStatus.kt
  app/src/main/java/com/woowa/banchan/domain/entity/OrderDetailSection.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/order/AddOrderUserCase.kt
  app/src/main/java/com/woowa/banchan/extensions/TimeStringConverter.kt
  app/src/main/java/com/woowa/banchan/ui/orderdetail/OrderDetailAdapter.kt
  app/src/main/res/values/strings.xml
  buildSrc/src/main/java/Dependencies.kt
Labels: feature, day15

#109 네트워크 감지 기능 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/woowa/banchan/ui/MainActivity.kt
  app/src/main/java/com/woowa/banchan/ui/SplashActivity.kt
  app/src/main/java/com/woowa/banchan/ui/cart/CartFragment.kt
  app/src/main/java/com/woowa/banchan/ui/cart/CartScreen.kt
  app/src/main/java/com/woowa/banchan/ui/cart/CartUiState.kt
  app/src/main/java/com/woowa/banchan/ui/cart/CartViewModel.kt
  app/src/main/java/com/woowa/banchan/ui/customview/LoadingFragment.kt
  app/src/main/java/com/woowa/banchan/ui/main/MainActivity.kt
  app/src/main/java/com/woowa/banchan/ui/main/tabs/ProductsViewModel.kt
  app/src/main/java/com/woowa/banchan/ui/main/tabs/home/HomeFragment.kt
  app/src/main/java/com/woowa/banchan/ui/main/tabs/home/PlanViewModel.kt
  app/src/main/java/com/woowa/banchan/ui/main/tabs/maindish/MainDishFragment.kt
  app/src/main/java/com/woowa/banchan/ui/main/tabs/side/SideFragment.kt
  app/src/main/java/com/woowa/banchan/ui/main/tabs/soup/SoupFragment.kt
  app/src/main/java/com/woowa/banchan/ui/network/ConnectivityObserver.kt
  app/src/main/java/com/woowa/banchan/ui/network/NetworkConnectivityObserver.kt
  app/src/main/java/com/woowa/banchan/ui/recently/RecentlyViewModel.kt
  app/src/main/res/anim/rotate_360.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_loading.xml
  app/src/main/res/layout/fragment_maindish.xml
  app/src/main/res/layout/fragment_side.xml
  app/src/main/res/layout/fragment_soup.xml
  app/src/main/res/values/strings.xml
Labels: feature, day15

#110 가로 스크롤 상에서 세로 스크롤이 안되던 문제 해결
  app/src/main/java/com/woowa/banchan/ui/main/tabs/home/HorizontalScrollListener.kt
  app/src/main/java/com/woowa/banchan/ui/main/tabs/home/NestedScrollListener.kt
  app/src/main/java/com/woowa/banchan/ui/main/tabs/home/PlanAdapter.kt
Labels: fix, day15

#111 앱 바 아이콘 동적 변경 적용
  app/src/main/java/com/woowa/banchan/data/local/entity/OrderInfoView.kt
  app/src/main/java/com/woowa/banchan/data/local/repository/OrderRepositoryImpl.kt
  app/src/main/java/com/woowa/banchan/domain/entity/OrderInfo.kt
  app/src/main/java/com/woowa/banchan/ui/bindingadapter/BanchanAppbarBindingAdapter.kt
  app/src/main/java/com/woowa/banchan/ui/cart/CartFragment.kt
  app/src/main/java/com/woowa/banchan/ui/detail/DetailFragment.kt
  app/src/main/java/com/woowa/banchan/ui/main/MainFragment.kt
  app/src/main/java/com/woowa/banchan/ui/order/OrderListAdapter.kt
  app/src/main/java/com/woowa/banchan/ui/orderdetail/OrderDetailViewModel.kt
  app/src/main/res/layout/fragment_detail.xml
Labels: feature, ui, day16

#115 주문 알람 설정(알람 매니저, 노티피케이션, 워크 매니저)
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/woowa/banchan/BanchanApplication.kt
  app/src/main/java/com/woowa/banchan/data/local/repository/OrderRepositoryImpl.kt
  app/src/main/java/com/woowa/banchan/ui/AlarmBroadcastReceiver.kt
  app/src/main/java/com/woowa/banchan/ui/DeliveryWorker.kt
  app/src/main/java/com/woowa/banchan/ui/Notifications.kt
  app/src/main/java/com/woowa/banchan/ui/cart/CartFragment.kt
  app/src/main/java/com/woowa/banchan/ui/cart/CartViewModel.kt
  app/src/main/java/com/woowa/banchan/ui/main/MainActivity.kt
  app/src/main/java/com/woowa/banchan/ui/order/OrderViewModel.kt
  app/src/main/java/com/woowa/banchan/ui/orderdetail/OrderDetailFragment.kt
  app/src/main/java/com/woowa/banchan/ui/orderdetail/OrderDetailViewModel.kt
  app/src/main/res/layout/fragment_order_detail.xml
Labels: feature, day16

#120 네트워크 버전 호환
  app/src/main/java/com/woowa/banchan/ui/MainActivity.kt
Labels: feature, day16

#122 앱 바 숨겨진 아래 화면의 버튼이 눌리는 현상 수정 및 Empty 화면 추가
  app/src/main/java/com/woowa/banchan/ui/customview/BanchanAppbar.kt
  app/src/main/java/com/woowa/banchan/ui/screen/cart/components/CartColumn.kt
  app/src/main/java/com/woowa/banchan/ui/screen/order/OrderFragment.kt
  app/src/main/java/com/woowa/banchan/ui/screen/recently/RecentlyFragment.kt
  app/src/main/res/anim/translate_infinity.xml
  app/src/main/res/drawable/empty.png
  app/src/main/res/drawable/lockandlock.png
  app/src/main/res/layout/fragment_order.xml
  app/src/main/res/layout/fragment_recently.xml
  app/src/main/res/layout/view_app_bar.xml
  app/src/main/res/values/strings.xml
Labels: ui, day16

#121 최근 본 상품 장바구니 표기여부(장바구니와 최근 본 상품 비교하기)
  app/src/main/java/com/woowa/banchan/data/local/datasource/RecentlyViewedLocalDataSource.kt
  app/src/main/java/com/woowa/banchan/data/local/repository/RecentlyViewedRepositoryImpl.kt
  app/src/main/java/com/woowa/banchan/di/UseCaseModule.kt
  app/src/main/java/com/woowa/banchan/domain/entity/RecentlyViewed.kt
  app/src/main/java/com/woowa/banchan/domain/repository/RecentlyViewedRepository.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/recentlyviewed/GetAllRecentlyViewedUseCase.kt
  app/src/main/java/com/woowa/banchan/ui/screen/recently/RecentlyFragment.kt
  app/src/main/res/layout/item_recently.xml
Labels: feature, day16

#125 Bottom Sheet 가로 화면 대응
  app/build.gradle.kts
  app/src/main/java/com/woowa/banchan/domain/entity/Product.kt
  app/src/main/java/com/woowa/banchan/ui/customview/CartBottomSheet.kt
  app/src/main/java/com/woowa/banchan/ui/screen/main/tabs/maindish/MainDishFragment.kt
  app/src/main/java/com/woowa/banchan/ui/screen/main/tabs/plan/PlanFragment.kt
  app/src/main/java/com/woowa/banchan/ui/screen/main/tabs/side/SideFragment.kt
  app/src/main/java/com/woowa/banchan/ui/screen/main/tabs/soup/SoupFragment.kt
  app/src/main/java/com/woowa/banchan/ui/screen/recently/RecentlyFragment.kt
Labels: ui, fix, day16

#123 appbar / animation / notification UI 문제 일부 수정
  app/build.gradle.kts
  app/src/main/java/com/woowa/banchan/domain/entity/Product.kt
  app/src/main/java/com/woowa/banchan/ui/bindingadapter/BanchanAppbarBindingAdapter.kt
  app/src/main/java/com/woowa/banchan/ui/customview/BanchanAppbar.kt
  app/src/main/java/com/woowa/banchan/ui/customview/CartBottomSheet.kt
  app/src/main/java/com/woowa/banchan/ui/screen/main/MainFragment.kt
  app/src/main/java/com/woowa/banchan/ui/screen/main/tabs/maindish/MainDishFragment.kt
  app/src/main/java/com/woowa/banchan/ui/screen/main/tabs/plan/PlanFragment.kt
  app/src/main/java/com/woowa/banchan/ui/screen/main/tabs/side/SideFragment.kt
  app/src/main/java/com/woowa/banchan/ui/screen/main/tabs/soup/SoupFragment.kt
  app/src/main/java/com/woowa/banchan/ui/screen/order/OrderFragment.kt
  app/src/main/java/com/woowa/banchan/ui/screen/recently/RecentlyFragment.kt
  app/src/main/res/layout/fragment_order.xml
  app/src/main/res/layout/fragment_order_detail.xml
  app/src/main/res/layout/fragment_recently.xml
  app/src/main/res/values/strings.xml
Labels: ui, fix, day16

#126 탭 화면 uiEvent 생성
  app/src/main/java/com/woowa/banchan/ui/screen/main/tabs/ProductUiEvent.kt
  app/src/main/java/com/woowa/banchan/ui/screen/main/tabs/ProductsUiState.kt
  app/src/main/java/com/woowa/banchan/ui/screen/main/tabs/ProductsViewModel.kt
  app/src/main/java/com/woowa/banchan/ui/screen/main/tabs/maindish/MainDishFragment.kt
  app/src/main/java/com/woowa/banchan/ui/screen/main/tabs/plan/PlanFragment.kt
  app/src/main/java/com/woowa/banchan/ui/screen/main/tabs/plan/PlanUiState.kt
  app/src/main/java/com/woowa/banchan/ui/screen/main/tabs/plan/PlanViewModel.kt
  app/src/main/java/com/woowa/banchan/ui/screen/main/tabs/side/SideFragment.kt
  app/src/main/java/com/woowa/banchan/ui/screen/main/tabs/soup/SoupFragment.kt
Labels: refactor, day17

#139 Git Action unit test 설정
  .github/workflows/android_build.yml
Labels: chore, day17

#140 뜨끈한 국물 요리, 정갈한 밑반찬 가로 화면에 스피너 유지
  app/src/main/java/com/woowa/banchan/ui/screen/main/tabs/maindish/MainDishFragment.kt
  app/src/main/java/com/woowa/banchan/ui/screen/main/tabs/side/SideFragment.kt
  app/src/main/java/com/woowa/banchan/ui/screen/main/tabs/soup/SoupFragment.kt
  app/src/main/res/values/strings.xml
Labels: day18

#141 장바구니 이슈 해결
  .github/workflows/android_build.yml
  app/src/main/java/com/woowa/banchan/ui/screen/cart/CartFragment.kt
  app/src/main/java/com/woowa/banchan/ui/screen/cart/CartScreen.kt
  app/src/main/java/com/woowa/banchan/ui/screen/cart/CartUiState.kt
  app/src/main/java/com/woowa/banchan/ui/screen/cart/CartViewModel.kt
  app/src/main/java/com/woowa/banchan/ui/screen/cart/components/CartColumn.kt
  app/src/main/java/com/woowa/banchan/ui/screen/cart/components/CartItemEmpty.kt
  app/src/main/java/com/woowa/banchan/ui/screen/cart/components/CartItemRow.kt
  app/src/main/java/com/woowa/banchan/ui/screen/cart/components/CartOrderButton.kt
Labels: fix, refactor, day18

#143 주문 테스트 코드 추가
  app/src/test/java/com/woowa/banchan/data/local/order/OrderPagingSourceTest.kt
  app/src/test/java/com/woowa/banchan/data/local/order/OrderRepositoryTest.kt
Labels: test, day18

#146 앱 죽은 상태에서의 알림 클릭 시 화면 전환
  app/src/main/java/com/woowa/banchan/ui/MainActivity.kt
Labels: fix, day18

#147 바텀 시트 수량 상태 유지
  app/src/main/java/com/woowa/banchan/ui/customview/CartBottomSheet.kt
  app/src/main/java/com/woowa/banchan/ui/screen/cart/CartFragment.kt
  app/src/main/res/layout/fragment_bottom_sheet.xml
Labels: fix, day18

#149 장바구니 변화에 따라 job 객체 제어
  app/src/main/java/com/woowa/banchan/ui/MainActivity.kt
  app/src/main/java/com/woowa/banchan/ui/screen/main/tabs/ProductsViewModel.kt
  app/src/main/java/com/woowa/banchan/ui/screen/main/tabs/maindish/MainDishFragment.kt
  app/src/main/java/com/woowa/banchan/ui/screen/main/tabs/plan/PlanFragment.kt
  app/src/main/java/com/woowa/banchan/ui/screen/main/tabs/side/SideFragment.kt
  app/src/main/java/com/woowa/banchan/ui/screen/main/tabs/soup/SoupFragment.kt
Labels: fix, day18

#154 App Distribution & Crashlytics 설정
  app/build.gradle.kts
  app/google-services.json
  build.gradle.kts
  buildSrc/src/main/java/Dependencies.kt
Labels: chore, day19

#155 장바구니 체크 이슈
  app/src/main/java/com/woowa/banchan/ui/screen/cart/CartScreen.kt
  app/src/main/java/com/woowa/banchan/ui/screen/cart/components/CartItemRow.kt
Labels: fix, day19

#158 주문내역 실시간 업데이트 이슈
  app/build.gradle.kts
  app/src/main/java/com/woowa/banchan/data/local/dao/OrderDao.kt
  app/src/main/java/com/woowa/banchan/data/local/datasource/OrderDataSource.kt
  app/src/main/java/com/woowa/banchan/data/local/datasource/OrderLocalDataSource.kt
  app/src/main/java/com/woowa/banchan/data/local/datasource/OrderPagingSource.kt
  app/src/main/java/com/woowa/banchan/data/local/repository/OrderRepositoryImpl.kt
  app/src/main/java/com/woowa/banchan/domain/repository/OrderRepository.kt
  app/src/main/java/com/woowa/banchan/ui/screen/order/OrderViewModel.kt
  app/src/test/java/com/woowa/banchan/data/local/order/OrderPagingSourceTest.kt
  buildSrc/src/main/java/Dependencies.kt
Labels: fix, day19

#160 레이아웃 패딩 수정
  app/src/main/java/com/woowa/banchan/ui/screen/cart/components/CartItemRow.kt
  app/src/main/java/com/woowa/banchan/ui/screen/cart/components/CartOrderButton.kt
  app/src/main/java/com/woowa/banchan/ui/screen/cart/components/RecentlyViewedColumn.kt
  app/src/main/res/layout/fragment_dialog.xml
  app/src/main/res/layout/item_recently.xml
Labels: fix, day19

#163 알림 에러 대응
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/woowa/banchan/ui/MainActivity.kt
  app/src/main/java/com/woowa/banchan/ui/screen/Notifications.kt
Labels: fix, day19

#166 장바구니 변경에 대해 상품 상세화면에 반영되지 않는 문제 해결
  app/src/main/java/com/woowa/banchan/ui/screen/detail/DetailFragment.kt
Labels: fix, day19

#168 네트워크 감지 다이얼로그 중첩 문제 해결 + 부수적으로 생긴 이슈
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/woowa/banchan/ui/MainActivity.kt
  app/src/main/java/com/woowa/banchan/ui/customview/LoadingFragment.kt
  app/src/main/java/com/woowa/banchan/ui/screen/Notifications.kt
  app/src/main/java/com/woowa/banchan/ui/screen/main/tabs/maindish/MainDishFragment.kt
  app/src/main/java/com/woowa/banchan/ui/screen/main/tabs/plan/PlanFragment.kt
  app/src/main/java/com/woowa/banchan/ui/screen/main/tabs/plan/PlanViewModel.kt
  app/src/main/java/com/woowa/banchan/ui/screen/main/tabs/side/SideFragment.kt
  app/src/main/java/com/woowa/banchan/ui/screen/main/tabs/soup/SoupFragment.kt
Labels: fix, day20

#170 주문할 시 장바구니 빈 화면이 보이는 현상 해결 & 네트워크 끊김 현상 개선
  app/src/main/java/com/woowa/banchan/ui/MainActivity.kt
  app/src/main/java/com/woowa/banchan/ui/screen/cart/CartFragment.kt
  app/src/main/java/com/woowa/banchan/ui/screen/cart/CartViewModel.kt
  app/src/main/java/com/woowa/banchan/ui/screen/detail/DetailFragment.kt
  app/src/main/java/com/woowa/banchan/ui/screen/main/MainFragment.kt
  app/src/main/java/com/woowa/banchan/ui/screen/main/tabs/maindish/MainDishFragment.kt
  app/src/main/java/com/woowa/banchan/ui/screen/main/tabs/plan/PlanFragment.kt
  app/src/main/java/com/woowa/banchan/ui/screen/main/tabs/side/SideFragment.kt
  app/src/main/java/com/woowa/banchan/ui/screen/main/tabs/soup/SoupFragment.kt
Labels: fix, day20

#175 바텀 시트 중복 호출 문제 해결
  app/src/main/java/com/woowa/banchan/ui/extensions/ViewExtension.kt
  app/src/main/java/com/woowa/banchan/ui/screen/main/tabs/adapter/ProductAdapter.kt
  app/src/main/java/com/woowa/banchan/ui/screen/recently/RecentlyAdapter.kt
Labels: fix, day20

#174 네트워크 다이얼로그 + 화면 회전 이슈 해결
  app/src/main/java/com/woowa/banchan/ui/MainActivity.kt
  app/src/main/java/com/woowa/banchan/ui/screen/main/tabs/maindish/MainDishFragment.kt
  app/src/main/java/com/woowa/banchan/ui/screen/main/tabs/plan/PlanFragment.kt
  app/src/main/java/com/woowa/banchan/ui/screen/main/tabs/side/SideFragment.kt
  app/src/main/java/com/woowa/banchan/ui/screen/main/tabs/soup/SoupFragment.kt
  app/src/main/res/layout/fragment_main.xml
Labels: fix, day20

#177 수량 직접 입력 예외 처리 해결
  app/src/main/java/com/woowa/banchan/ui/screen/cart/components/CartItemRow.kt
Labels: fix, day21

#180 Git Action App Distribution 설정
  .github/workflows/android_build_cd.yml
Labels: chore, day21

#183 불필요한 정보 제거
  app/src/main/java/com/woowa/banchan/ui/customview/BanchanAppbar.kt
  app/src/main/java/com/woowa/banchan/ui/screen/cart/CartScreen.kt
  app/src/main/java/com/woowa/banchan/ui/screen/cart/components/CartOrderButton.kt
  app/src/main/java/com/woowa/banchan/ui/screen/main/tabs/maindish/MainDishFragment.kt
  app/src/main/java/com/woowa/banchan/ui/screen/main/tabs/plan/PlanFragment.kt
  app/src/main/java/com/woowa/banchan/ui/screen/main/tabs/side/SideFragment.kt
  app/src/main/java/com/woowa/banchan/ui/screen/main/tabs/soup/SoupFragment.kt
Labels: fix, day21

#184 프로젝트 v1.0.1 배포
  .github/workflows/android_build_cd.yml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/woowa/banchan/ui/MainActivity.kt
  app/src/main/java/com/woowa/banchan/ui/customview/BanchanAppbar.kt
  app/src/main/java/com/woowa/banchan/ui/customview/LoadingFragment.kt
  app/src/main/java/com/woowa/banchan/ui/extensions/ViewExtension.kt
  app/src/main/java/com/woowa/banchan/ui/screen/cart/CartFragment.kt
  app/src/main/java/com/woowa/banchan/ui/screen/cart/CartScreen.kt
  app/src/main/java/com/woowa/banchan/ui/screen/cart/CartViewModel.kt
  app/src/main/java/com/woowa/banchan/ui/screen/cart/components/CartItemRow.kt
  app/src/main/java/com/woowa/banchan/ui/screen/cart/components/CartOrderButton.kt
  app/src/main/java/com/woowa/banchan/ui/screen/cart/components/KeyboardAsState.kt
  app/src/main/java/com/woowa/banchan/ui/screen/cart/components/RecentlyViewedColumn.kt
  app/src/main/java/com/woowa/banchan/ui/screen/detail/DetailFragment.kt
  app/src/main/java/com/woowa/banchan/ui/screen/main/tabs/ProductsViewModel.kt
  app/src/main/java/com/woowa/banchan/ui/screen/main/tabs/adapter/ProductAdapter.kt
  app/src/main/java/com/woowa/banchan/ui/screen/main/tabs/adapter/TypeFilterAdapter.kt
  app/src/main/java/com/woowa/banchan/ui/screen/main/tabs/maindish/MainDishFragment.kt
  app/src/main/java/com/woowa/banchan/ui/screen/main/tabs/plan/PlanFragment.kt
  app/src/main/java/com/woowa/banchan/ui/screen/main/tabs/plan/PlanViewModel.kt
  app/src/main/java/com/woowa/banchan/ui/screen/main/tabs/side/SideFragment.kt
  app/src/main/java/com/woowa/banchan/ui/screen/main/tabs/soup/SoupFragment.kt
  app/src/main/java/com/woowa/banchan/ui/screen/recently/RecentlyAdapter.kt
  app/src/main/res/layout/fragment_dialog.xml
  app/src/main/res/layout/fragment_main.xml
  app/src/main/res/layout/item_recently.xml
Labels: feature, day21

#185 화면 회전에 따른 알림창 크기 대응
  app/src/main/java/com/woowa/banchan/ui/customview/CartDialog.kt
Labels: ui, fix, day21
